export default [
  {
    key: 1,
    title: '燃尽图',
    description: '跟踪记录所有问题的剩余工作工作时间，这有助于在团队管理方面取得更进一步的掌控与把握。',
    path: '/agile/reporthost/burndownchart',
    pic: 'burndownchart',
    report_type: '敏捷',
    icon: '',
    sort: 1,
  },
  {
    key: 2,
    title: 'Sprint报告',
    description: '了解每个冲刺中完成、进行和退回待办的工作。这有助于您确定团队的工作量是否超额。',
    path: '/agile/reporthost/sprintReport',
    pic: 'sprint',
    report_type: '敏捷',
    icon: '',
    sort: 3,
  },
  {
    key: 11,
    title: '累积流量图',
    description: '显示状态的问题，这有助于您识别潜在的瓶颈， 需要对此进行调查。',
    path: '/agile/reporthost/accumulation',
    pic: 'accumulation',
    report_type: '敏捷',
    icon: '',
    sort: 2,
  },
  {
    key: 12,
    title: '燃尽图',
    description: '跟踪记录所有问题的剩余工作工作时间，这有助于在团队管理方面取得更进一步的掌控与把握。',
    path: '/agile/reporthost/burndownchart',
    pic: 'burndownchart',
    report_type: '敏捷',
    icon: '',
    sort: 1,
  },
  {
    key: 13,
    title: 'Sprint报告',
    description: '了解每个冲刺中完成、进行和退回待办的工作。这有助于您确定团队的工作量是否超额。',
    path: '/agile/reporthost/sprintReport',
    pic: 'sprint',
    report_type: '敏捷',
    icon: '',
    sort: 3,
  },
  {
    key: 4,
    title: '版本报告',
    description: '跟踪对应的版本发布日期，这有助于您监控此版本是否按时发布，以便工作滞后时能采取行动。',
    path: '/agile/reporthost/versionReport',
    pic: 'versionReport',
    report_type: '测试',
    icon: '',
    sort: 2,
  },
  {
    key: 5,
    title: '添加速度图',
    description: '了解每个冲刺中完成、进行和退回待办的工作。这有助于您确定团队的工作量是否超额。',
    path: '/agile/reporthost/sprintReport',
    pic: 'sprint',
    report_type: 'Devops',
    icon: '',
    sort: 3,
  },
  {
    key: 6,
    title: 'epic报告图',
    description: '显示状态的问题，这有助于您识别潜在的瓶颈， 需要对此进行调查。',
    path: '/agile/reporthost/accumulation',
    pic: 'accumulation',
    report_type: 'Devops',
    icon: '',
    sort: 2,
  },
  {
    key: 7,
    title: '饼图',
    description: '跟踪对应的版本发布日期，这有助于您监控此版本是否按时发布，以便工作滞后时能采取行动。',
    path: '/agile/reporthost/versionReport',
    pic: 'versionReport',
    report_type: 'Devops',
    icon: '',
    sort: 1,
  },
];
