const componentsObj = {
  // 星标项目
  starTarget: {
    x: 0,
    y: 0,
    w: 9,
    h: 2,
    minH: 2,
    minW: 9,
    static: true,
    isDraggable: false,
    isResizable: false,
    i: 'starTarget',
    name: 'starTarget',
    type: 'starTarget',
  },
  // 用户信息
  selfInfo: {
    x: 9,
    y: 0,
    h: 2,
    w: 3,
    minH: 2,
    minW: 2,
    static: true,
    isDraggable: false,
    isResizable: false,
    i: 'selfInfo',
    name: 'selfInfo',
    type: 'selfInfo',
  },
  todoQustions: {
    x: 0,
    y: 2,
    h: 4,
    w: 5,
    minH: 2,
    minW: 4,
    static: true,
    isDraggable: false,
    isResizable: false,
    i: 'todoQustions',
    name: 'todoQustions',
    type: 'todoQustions',

  },
  // 待审核模块
  todoThings: {
    x: 5,
    y: 2,
    h: 4,
    w: 4,
    minH: 2,
    minW: 3,
    static: true,
    isDraggable: false,
    isResizable: false,
    i: 'todoThings',
    name: 'todoThings',
    type: 'todoThings',
  },

  // 最近使用应用服务
  serviceList: {
    x: 9,
    y: 2,
    h: 5,
    w: 3,
    minH: 2,
    minW: 3,
    static: true,
    isDraggable: false,
    isResizable: false,
    i: 'serviceList',
    name: 'serviceList',
    type: 'serviceList',
  },
  // 快速链接
  quickLink: {
    x: 0,
    y: 6,
    h: 6,
    w: 4,
    minH: 2,
    minW: 3,
    static: true,
    isDraggable: false,
    isResizable: false,
    i: 'quickLink',
    name: 'quickLink',
    type: 'quickLink',
  },
  // 文档
  doc: {
    x: 4,
    y: 6,
    h: 6,
    w: 5,
    minH: 2,
    minW: 4,
    static: true,
    isDraggable: false,
    isResizable: false,
    i: 'doc',
    name: 'doc',
    type: 'doc',

  },

  // 最近使用环境
  envList: {
    x: 9,
    y: 7,
    h: 5,
    w: 3,
    minH: 2,
    minW: 3,
    static: true,
    isDraggable: false,
    isResizable: false,
    i: 'envList',
    name: 'envList',
    type: 'envList',
  },
};

export default componentsObj;
