const BUCKET_NAME_PUBLIC = 'public';
const BUCKET_NAME_PRIVATE = 'private';
const BUCKET_NAME_DIRECTORY_AGILE = 'agile-service';
const BUCKET_NAME_DIRECTORY_TEST = 'test-service';
const BUCKET_NAME_DIRECTORY_KNOWLEDGE = 'knowledgebase-service';

export {
  BUCKET_NAME_PUBLIC,
  BUCKET_NAME_PRIVATE,
  BUCKET_NAME_DIRECTORY_AGILE,
  BUCKET_NAME_DIRECTORY_TEST,
  BUCKET_NAME_DIRECTORY_KNOWLEDGE,
};
