// 这里用来配置需要隐藏菜单的路由

import {
  AGILE_WORK_CALENDAR_PATH,
  APPLICATIONS_PATH,
  ENTERPRISE_ADDRESS,
  HOMEPAGE_PATH,
  KNOWLEDGE_ORG_PATH,
  MARKET_PATH,
  PROJECTS_HOME_PATH,
} from './PATHS';

const HIDDEN_MENU_PATHS_COLLECTION = [
  PROJECTS_HOME_PATH,
  APPLICATIONS_PATH,
  MARKET_PATH,
  KNOWLEDGE_ORG_PATH,
  HOMEPAGE_PATH,
  AGILE_WORK_CALENDAR_PATH,
  ENTERPRISE_ADDRESS,
] as const;

export {
  HIDDEN_MENU_PATHS_COLLECTION,
};
