// 这里用来配置需要隐藏头部的路由

import { ENTERPRISE_ADDRESS, KNOWLEDGE_ORG_TEMPLATE_PREVIEW_PATH } from './PATHS';

const HIDDEN_HEAD_PATHS_COLLECTION = [
  ENTERPRISE_ADDRESS,
  KNOWLEDGE_ORG_TEMPLATE_PREVIEW_PATH,
] as const;

export {
  HIDDEN_HEAD_PATHS_COLLECTION,
};
